# Configuração para usar o Banco de Dados H2 (em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 (Para você acessar no navegador)
spring.h2.console.enabled=true


# Comandos Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081