
# CONFIGURAÇÃO DO BANCO NEON (POSTGRESQL)


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE E SERVIDOR
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# Faz o Spring Boot rodar arquivo data.sql DEPOIS de criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never