
# CONFIGURAÇÃO DO BANCO NEON (POSTGRESQL)


spring.datasource.url=jdbc:postgresql://ep-misty-firefly-acfz2h9l.sa-east-1.aws.neon.tech/neondb?sslmode=require

# usuário
spring.datasource.username=neondb_owner

# Senha
spring.datasource.password=npg_aq3cRQFDZX5k


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE E SERVIDOR
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081

# Faz o Spring Boot rodar arquivo data.sql DEPOIS de criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never